### ISSUE TITLE
[question] Creating a slim "builder" image for GitLab CI & Serenity (exit code 199 issue)

### ISSUE THREAD

**Issue by drkstr101** [serenity-js/serenity-js#707] opened 2020-12-07 07:35 UTC
Greetings all,

I was hoping to create a minimal Docker image to use for gitlab-ci tasks, and I thought I had all the boxes checked, but I am still getting one last error I'm having trouble diagnosting, and I was hoping one who is a bit more familiar with what's going on could point me in the right direction.

Here is where I'm at...

```Dockerfile
FROM openjdk:11-jdk-slim as jdk11

FROM node:12-alpine

# Copy In JDK
COPY --from=jdk11 /usr/local/openjdk-11 /usr/lib/jvm/default-jvm
ENV JAVA_HOME=/usr/lib/jvm/default-jvm
ENV PATH=/usr/lib/jvm/default-jvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# Installs latest Chromium package.
RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/main" > /etc/apk/repositories \
    && echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories \
    && echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories \
    && echo "http://dl-cdn.alpinelinux.org/alpine/v3.12/main" >> /etc/apk/repositories \
    && apk upgrade -U -a \
    && apk add \
    libstdc++ \
    chromium \
    harfbuzz \
    nss \
    freetype \
    ttf-freefont \
    font-noto-emoji \
    wqy-zenhei \
    && rm -rf /var/cache/* \
    && mkdir /var/cache/apk;

COPY local.conf /etc/fonts/local.conf

# Just grasping at straws... prob not required
RUN mkdir -p /opt/google && \
    ln -s /usr/bin/chromium-browser /usr/bin/google-chrome && \
    ln -s /usr/lib/chromium /opt/google/chrome;

ENV CHROME_BIN=/usr/bin/google-chrome \
    CHROME_PATH=/opt/google/chrome;

# --EOF--
# Below this point is simply for debugging purposes...

WORKDIR /app
ADD . .

RUN yarn && yarn webdriver-manager update

RUN google-chrome --version

RUN yarn serenity:test --verbose
```

    webdriver-manager: using local installed version 12.1.7
    [07:19:31] I/update - chromedriver: file exists /app/node_modules/webdriver-manager/selenium/chromedriver_87.0.4280.88.zip
    [07:19:31] I/update - chromedriver: unzipping chromedriver_87.0.4280.88.zip
    [07:19:31] I/update - chromedriver: setting permissions to 0755 for /app/node_modules/webdriver-manager/selenium/chromedriver_87.0.4280.88
    [07:19:31] I/update - chromedriver: chromedriver_87.0.4280.88 up to date
    [07:19:31] I/update - selenium standalone: file exists /app/node_modules/webdriver-manager/selenium/selenium-server-standalone-3.141.59.jar
    [07:19:31] I/update - selenium standalone: selenium-server-standalone-3.141.59.jar up to date
    [07:19:31] I/update - geckodriver: file exists /app/node_modules/webdriver-manager/selenium/geckodriver-v0.28.0.tar.gz
    [07:19:31] I/update - geckodriver: unzipping geckodriver-v0.28.0.tar.gz
    [07:19:32] I/update - geckodriver: setting permissions to 0755 for /app/node_modules/webdriver-manager/selenium/geckodriver-v0.28.0
    [07:19:32] I/update - geckodriver: geckodriver-v0.28.0 up to date
    Chromium 86.0.4240.111 

No problems so far, but as soon as I attempt to connect to `chromedriver`

    $ yarn workspace @watheia-ui/serenity test --verbose
    $ failsafe clean test:execute test:report --verbose
    [clean] npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1607325644105-0.3107788068955748/node but npm is using /usr/local/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
    [clean] 
    [clean] > @watheia-ui/serenity@1.0.0 clean /app/packages/serenity
    [clean] > rimraf target
    [clean] 
    [failsafe] Script 'clean' exited with code 0
    [test:execute] npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1607325644105-0.3107788068955748/node but npm is using /usr/local/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
    [test:execute] 
    [test:execute] > @watheia-ui/serenity@1.0.0 test:execute /app/packages/serenity
    [test:execute] > protractor ./protractor.conf.js
    [test:execute] 
    [test:execute] [07:20:45] I/launcher - Running 1 instances of WebDriver
    [test:execute] [07:20:45] I/direct - Using ChromeDriver directly...
    [test:execute] [07:20:45] E/launcher - spawn /app/node_modules/webdriver-manager/selenium/chromedriver_87.0.4280.88 ENOENT
    [test:execute] [07:20:45] E/launcher - Error: spawn /app/node_modules/webdriver-manager/selenium/chromedriver_87.0.4280.88 ENOENT
    [test:execute]     at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
    [test:execute]     at onErrorNT (internal/child_process.js:470:16)
    [test:execute]     at processTicksAndRejections (internal/process/task_queues.js:84:21)
    [test:execute] [07:20:45] E/launcher - Process exited with error code 199
    [test:execute] npm ERR! code ELIFECYCLE
    [test:execute] npm ERR! errno 199
    [test:execute] npm ERR! @watheia-ui/serenity@1.0.0 test:execute: `protractor ./protractor.conf.js`
    [test:execute] npm ERR! Exit status 199
    [test:execute] npm ERR! 
    [test:execute] npm ERR! Failed at the @watheia-ui/serenity@1.0.0 test:execute script.
    [test:execute] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
    [test:execute] 
    [test:execute] npm ERR! A complete log of this run can be found in:
    [test:execute] npm ERR!     /root/.npm/_logs/2020-12-07T07_20_45_769Z-debug.log
    [failsafe] Script 'test:execute' exited with code 199
    [test:report] npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1607325644105-0.3107788068955748/node but npm is using /usr/local/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
    [test:report] 
    [test:report] > @watheia-ui/serenity@1.0.0 test:report /app/packages/serenity
    [test:report] > serenity-bdd run --scripts-prepend-node-path --features ./features
    [test:report] 
    [test:report] Spawning: /usr/lib/jvm/default-jvm/bin/java -Dserenity.compress.filenames=true -DLOG_LEVEL=warn -Dlogback.configurationFile=/app/node_modules/@serenity-js/serenity-bdd/resources/logback.config.xml -jar node_modules/@serenity-js/serenity-bdd/cache/serenity-cli-2.1.10-all.jar --features ./features --destination target/site/serenity --source target/site/serenity --project serenity
    [test:report] Invoking Serenity BDD CLI has failed
    [test:report] Error: spawn /usr/lib/jvm/default-jvm/bin/java ENOENT
    [test:report]     at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
    [test:report]     at onErrorNT (internal/child_process.js:470:16)
    [test:report]     at processTicksAndRejections (internal/process/task_queues.js:84:21)
    [failsafe] Script 'test:report' exited with code 0
    [--verbose] npm info it worked if it ends with ok
    [--verbose] npm verb cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', '--verbose' ]
    [--verbose] npm info using npm@6.14.8
    [--verbose] npm info using node@v12.20.0
    [--verbose] Lifecycle scripts included in @watheia-ui/serenity:
    [--verbose]   postinstall
    [--verbose]     serenity-bdd update && webdriver-manager update
    [--verbose]   test
    [--verbose]     failsafe clean test:execute test:report
    [--verbose] 
    [--verbose] available via `npm run-script`:
    [--verbose]   clean
    [--verbose]     rimraf target
    [--verbose]   test:execute
    [--verbose]     protractor ./protractor.conf.js
    [--verbose]   test:execute:wip
    [--verbose]     protractor ./protractor.conf.js --cucumberOpts.tags=@wip
    [--verbose]   test:report
    [--verbose]     serenity-bdd run --scripts-prepend-node-path --features ./features
    [--verbose]   wip
    [--verbose]     failsafe clean test:execute:wip test:report
    [--verbose]   lint
    [--verbose]     tslint --project tsconfig.json --format stylish
    [--verbose] npm verb exit [ 0, true ]
    [--verbose] npm timing npm Completed in 82ms
    [--verbose] npm info ok 
    [failsafe] Script '--verbose' exited with code 0
    error Command failed with exit code 199.
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
    error Command failed.
    Exit code: 199
    Command: /usr/local/bin/node
    Arguments: /opt/yarn-v1.22.5/lib/cli.js test --verbose
    Directory: /app/packages/serenity
    Output:

I'ts always this `exit code 199`. I couldn't really find any relevant information, unless I just missed someones point in one of the existing threads on this topic. I can run the build just fine on localhost, both using direct-connect and remote selenium grid.

This image will be pulled for just about every push to source control, so my only real requirement here is to be as slim as possible, while still containing required featureset. End-game is to probably just spin up a Zelenium Grid on demand, and just keep chromedriver out of the base image, but my DevOps Fu isn't this strong yet.

Any suggestions on how to go about debugging the issue further? I'm stuck on where to go from here...

Full build pipeline for context: https://gitlab.com/watheia/lab/watheia-ui/-/jobs/893885446

Cheers, and thanks in advance for your time!

~Aaron

**Comment by jan-molak** [comment] 2020-12-07 17:41
Hey @drkstr101 and welcome to the Serenity/JS community! 

I'd start with this [suggestion for Chromium](https://sites.google.com/a/chromium.org/chromedriver/help/chrome-doesn-t-start).

Also, I'm wondering if the issue could be caused by ChromeDriver and Chrome being of a different version?
Since the browser is part of the runner, consider installing [chromedriver](https://pkgs.alpinelinux.org/package/edge/community/x86_64/chromium-chromedriver) via `apk` too.
The advantage of installing both via `apk` is that they'd be compatible and you could avoid running into issues where chromedriver downloaded by `webdriver-manager` is newer than Chrome provided by `apk`

Does this help?
Jan

**Comment by viper3400** [comment] 2022-10-23 14:55
Hi @drkstr101 , this issue is quite old. Have you been able to solve your issues? Can we close this one?

**Comment by viper3400** [comment] 2022-12-04 15:07
I guess we can close this issue. Please do not hesitate to raise a new one if the problem still exists. Just in case, please provide an update about your current setup and issues, then.

**Closed by viper3400** 2022-12-04 15:07 UTC
Labels: question, awaiting feedback
