### ISSUE TITLE
Issue with REST API Call

### ISSUE THREAD

**Issue by Krithikmano** [serenity-js/serenity-js#709] opened 2020-12-09 23:48 UTC
1.I tried to make REST Call, it is not giving any response in console as well as report. But i deliberately updated incorrect url then it showing response in report. 

2. How to print response body in the console. I try to print and it is showing as anonymous question. Refer the screenshot 

Note:
I am not using screenplay. 

![79F60862-1A7A-4BAE-9641-569887EF338B](https://user-images.githubusercontent.com/28629290/101702466-80535a00-3a46-11eb-9b29-b1603ecebda8.jpeg)

![E61ABC78-BB2A-4808-B99B-F488E1F79AC3](https://user-images.githubusercontent.com/28629290/101702488-8e08df80-3a46-11eb-8d3b-4874248585b2.jpeg)

**Comment by jan-molak** [comment] 2020-12-10 00:35
Hi @Krithikmano and welcome to the Serenity/JS community!

Note that `actorCalled('Apisit').attemptsTo(...)` returns a ` Promise`, which the code sample in your post doesn't await for; because of this, you're not seeing what you're expecting to see because the method exits before it manages to do anything.

Also, `LastResponse.body()` is a [`Question`](https://serenity-js.org/handbook/design/questions.html), which you need to give to an `Actor`, so saying `console.log(LastResponse.body())` will simply print the question object rather than the actual body that you're after.

There's a dedicated interaction to [`Log`](https://serenity-js.org/modules/core/class/src/screenplay/interactions/Log.ts~Log.html). However, instead of just simply printing things to the console, it emits events that Serenity/JS reporters (like the [`ConsoleReporter`](https://serenity-js.org/modules/console-reporter/) or the [`SerenityBDDReporter`](https://serenity-js.org/modules/serenity-bdd/)) can listen to.

Try with a test scenario along those lines:
```
import { actorCalled, configure } from '@serenity-js/core';
import { ConsoleReporter } from '@serenity-js/console-reporter';

configure({
    crew: [ ConsoleReporter.withDefaultColourSupport() ]
});

actorCalled('Apisitt')
    .whoCan(CallAnApi.using(axiosInstance))
    .attemptsTo(
        Send.a(PostRequest.to(...)),
        Ensure.that(LastResponse.status(), equals(200)),
        Log.the(LastResponse.body()),
    ) // <- this returns Promise<void>

```

Hope this helps!
Jan

**Comment by Krithikmano** [comment] 2020-12-10 05:35
@jan-molak Thanks for the swift response. Now I could see the response in the report. I have few more questions

1. How to extract data from response body. Could you provide some example how to do it?

2. In my scenario, I want to reuse the response in many places. I don’t want to run every time that REST call. How to assign this response to global variable and extract value from response whenever it is needed?

3. Now I could see the response in the report but it is showing [[object],[Object]]. Is there any way to show real value. 

![EB4E8A11-DDF2-4148-8DB2-9976A9E41DC3](https://user-images.githubusercontent.com/28629290/101725745-cde7bb00-3a76-11eb-9a18-0422f66fab00.jpeg)



4. My scenario is combination of UI and API. In the report, it is not taking each page screenshot and also end of the step it is adding the step as  “Inspector takes screenshot of....

![4947F231-1437-4482-B3CF-85D302AC475A](https://user-images.githubusercontent.com/28629290/101725488-60d42580-3a76-11eb-8a05-efb8bcd55d79.jpeg)

**Comment by Krithikmano** [comment] 2020-12-25 03:20
@jan-molak  is it possible assign the api response to global variable? Is this feature available?

**Comment by jan-molak** [comment] 2020-12-27 18:05
> @jan-molak is it possible assign the api response to global variable? Is this feature available?

You can assign it to a _scoped_ variable with the scope being either one scenario or the entire test suite, depending on the scope your actor operates on.

To enable an actor to remember things they see you need to give them an ability to [`TakeNotes`](https://serenity-js.org/modules/core/class/src/screenplay/abilities/TakeNotes.ts~TakeNotes.html). With the ability in place, you tell the actor to [`TakeNote.of(LastResponse.body())`](https://serenity-js.org/modules/core/class/src/screenplay/interactions/TakeNote.ts~TakeNote.html#takenote), which you can then read as [`Note.of(LastRespoonse.body()`](https://serenity-js.org/modules/core/class/src/screenplay/questions/Note.ts~Note.html).

If you don't want to remember the entire response but just some of it, you can use the [`Question.map()`](https://serenity-js.org/modules/core/class/src/screenplay/Question.ts~Question.html#instance-method-map) method.

The links I've provided above contain a bunch of examples, so let me know if all this makes sense!

Jan

**Comment by Krithikmano** [comment] 2020-12-28 22:13
@jan-molak Thanks for the information. It is working now. 

Could you please provide the solution for the above 3 and 4 question?

**Comment by jan-molak** [comment] 2020-12-31 00:23
Hey @Krithikmano!

> 3. Now I could see the response in the report but it is showing [[object],[Object]]. Is there any way to show real value.

As per my comment in #718, could you please provide an example response you're trying to log so that I can try to reproduce?

> 4. My scenario is combination of UI and API. In the report, it is not taking each page screenshot and also end of the step it is adding the step as “Inspector takes screenshot of....

I'd suggest to use the Screenplay Pattern in your test scenarios and configure `Photographer.whoWill(TakePhotosOfInteractions)` to capture screenshots automatically. This way you could get rid of an explicit `Inspector`.

Does this help?

**Comment by Krithikmano** [comment] 2021-01-01 02:29
@jan-molak 

1. After implementing with screenplay I could resolve the 4th issue. Screenshot is coming for every page. 
2. Regarding api response issue in the report . Please refer the below endpoint and you can replicate it . This is get call

http://api.plos.org/search?q=title:DNA

![1BAF0FD1-4E1A-4E52-8901-BC2E4E2BA701](https://user-images.githubusercontent.com/28629290/103432538-fc544400-4ba5-11eb-8834-99c2e3d91269.jpeg)

**Comment by mjgalapon** [comment] 2021-01-17 23:18
@jan-molak follow-up question on remembering the previous response;

"To enable an actor to remember things they see you need to give them an ability to TakeNotes. With the ability in place, you tell the actor to TakeNote.of(LastResponse.body()), which you can then read as Note.of(LastRespoonse.body()."

If you noted many responses; how do you read a specific one from the memory? for instance, you need to take note of 4 responses from 4 different calls as they are related;

1. TakeNote.of(LastResponse.body()) -> from Authentication API (read "token" from response to be used on the 3rd API call)
2. TakeNote.of(LastResponse.body()) -> from Authorization API (read "control" from response to be used on the 3rd API call)
3 Use token and access on the 3rd call;

Send.a(PostRequest.to('/digital-security-exp-api/v1/security/user/session')
            .using(HeadersOfSecurity())
            .with({token: token from 1st api call above,
                      access:access from 2nd api call above})),





You then need different info from 4 different responses; how do you pull a sa

**Comment by mjgalapon** [comment] 2021-01-17 23:19
@jan-molak  follow-up question on remembering the previous response;

"To enable an actor to remember things they see you need to give them an ability to TakeNotes. With the ability in place, you tell the actor to TakeNote.of(LastResponse.body()), which you can then read as Note.of(LastRespoonse.body()."

If you noted many responses; how do you read a specific one from the memory? for instance, you need to take note of 4 responses from 4 different calls as they are related;

TakeNote.of(LastResponse.body()) -> from Authentication API (read "token" from response to be used on the 3rd API call)
TakeNote.of(LastResponse.body()) -> from Authorization API (read "control" from response to be used on the 3rd API call)
3 Use token and access on the 3rd call;
Send.a(PostRequest.to('url')
.using(HeadersOfSecurity())
.with({token: token from 1st api call above,
access:access from 2nd api call above})),

How do you achieve this setup?

**Comment by jan-molak** [comment] 2021-01-17 23:36
@mjgalapon - if you have more than one question of the same type, you can differentiate the notes by giving them distinct names. Check out this example from [TakeNote](https://serenity-js.org/modules/core/class/src/screenplay/interactions/TakeNote.ts~TakeNote.html#takenote) API docs:

```typescript
actor.attemptsTo(
     TakeNote.of(Text.of(Vouchers.code)).as('voucher code'),
     // ... add the product to a basket, go to checkout, etc.
     Ensure.that(Text.of(Vouchers.appliedVoucher), equals(Note.of('voucher code'))),
 );
```

If you want to merge answers to two questions into a single one, like in your code sample above:

```typescript
Send.a(PostRequest.to('url')
    .using(HeadersOfSecurity())
    .with({token: token from 1st api call above, access:access from 2nd api call above})), // merge two answers
```

You'll need to create a custom question, for example:

```typescript
const AccessRequest = (token: Answerable<string>, access: Answerable<string>) => 
    Question.about<{ token: string, access: string }>(`access request body`, actor => 
        Promise.all([                   // use Promise.all to wait until both answers are available
            actor.answer(token),        // use actor.answer to get the answer to a question
            actor.answer(access),
        ]).
        then(([ tokenValue, accessValue]) => ({ // return and object with token and access.
            token: tokenValue,
            access: accessValue,
        }))
    )
```

And then:
```typescript
Send.a(PostRequest.to('url')
    .using(HeadersOfSecurity())
    .with(AccessRequest(Note.of('token'), Note.of('access'))),
```

Does this make sense?

I'll look into logging the response to http://api.plos.org/search?q=title:DNA

**Comment by mjgalapon** [comment] 2021-01-22 17:46
@jan-molak  Sorry, I think I was not able to explain very well on the question previously.  And also my example is a bit off.  So here is my issue; (please bear with me);

I have a separate scenario from a different feature and step, it is authenticate user using a Login and Password;
So that scenario will have a LastResponse of token returned.  That token is intended to be used and shared for all the other features; 

So I save the LastResponse of the step into TakeNote.of(LastReponse.body(Token)).as("Token")

Now next scenario runs and I need to use that Token as header in the GetRequest;  (see below)

```
GetRequest.to('Url')
                .using({headers: {
                            'x-transaction-id': Guid.newGuid(),                            
                            'Authorization': Note.of("Token") or _Note.of("test").map(actor=>actualValue=>actualValue)_
                           }}
                ),
```
So with the above usage, I end up with the headers below on my request;

```
{headers: {
        'x-transaction-id': Guid.newGuid(),
        'Authorization': {"subject": "A note of Token", "description": "A note of Token"}
    }}
```

The response I get from above when I log the requests headers 
The solution you provided above to create a custom question would have probably worked if the intent is use it on the .with() to ask the question of 'what token to use'.  But in my particular scenario, it will be used as a general configuration for multiple scenarios.  

Thank you in advance.

**Comment by jan-molak** [comment] 2021-01-22 18:29
Right; what you can do is use to configure your actors to [`TakeNotes.usingASharedNotepad()`](https://serenity-js.org/modules/core/class/src/screenplay/abilities/TakeNotes.ts~TakeNotes.html#static-method-usingASharedNotepad), and have the actor get the token in a `BeforeAll` step (so it runs exactly once, before all the scenarios). With this setup, the notepad is shared across all the scenarios, so you can retrieve the note you've taken in `BeforeAll` in a scenario.

In this case, make sure to give your note a meaningful name like `Token`. Let me know if you'd like to set up a zoom call to walk through the code?

Hope this helps.

**Comment by mjgalapon** [comment] 2021-01-22 18:37
Yes I already have the usingSharedNotepad() enable for the actor.
So when I log the note; before I fire the request, it returns the token;

User logs:
```
A note of Token:
'Bearer g7FlW0HHJssaIIhsslksBlahblah'
```

Log.(Note.of("Token")),
GetRequest.to('Url')
                .using({headers: {
                            'x-transaction-id': Guid.newGuid(),                            
                            'Authorization': Note.of("Token") or _Note.of("Token").map(actor=>actualValue=>actualValue)
                           }}
                ),

**Closed** 2021-01-23 02:51 UTC
Labels: documentation, question

**Comment by jan-molak** [comment] 2021-01-23 02:56
@Krithikmano - version **2.20.1** improves the way HTTP responses are formatted. For example, for the `http://api.plos.org/search?q=title:DNA` you'll now get:

<img width="1017" alt="Screenshot 2021-01-23 at 02 40 59" src="https://user-images.githubusercontent.com/1089173/105566907-8f584800-5d26-11eb-8e02-55792945280a.png">
