### ISSUE TITLE
multiple browser's name in the report when having more rows of datatable

### ISSUE THREAD

**Issue by lucieneven** [serenity-js/serenity-js#499] opened 2020-03-11 20:42 UTC
Hi guys,

I'm writing this in the hope that someone can shed some light on the report. When I have only one row of datatable, everything looks fine with the html report generated. However, if I have multiple row of datatable, I'll see multiple browser name in the html report generated. 

During our test, I use Chrome, so I see 3 Chrome when I have 3 rows of datatable. 

Example is like below, the feature file use three rows of tables.

    Examples:
      | outageIssue                 | phoneNumber | emailAddress             | contactNumber |
      | My lights are out           | 6109338069  | user_8507855029@test.com | 6109338069    |
      | My lights are partially out | 6109338069  | user_8507855029@test.com | 6109338069    |
      | Dim or Flickering lights    | 6109338069  | user_8507855029@test.com | 6109338069    |

In the html report, go to Scenario details, 

I'll see something like below:

CHROME, CHROME, CHROME user is not authenticated and wants to ....

I shared the snapshot with this links. 

https://1drv.ms/u/s!AteBeCiYQ0HTnYZixAdOTH-R6_Ec0Q?e=l0VB5Q

Hopefully it could be accessible!

I didn't do much thing in the protractor.conf.js. I'm wondering if this is a feature or defect or just something I can configure somewhere in the protractor.conf.js or any other file. 

Please anyone advise a few lines here, thanks so much!

Lucien

**Comment by jan-molak** [comment] 2020-03-12 11:13
Hi @lucieneven and thanks for reporting the issue. Could you please use the [`serenity-js-cucumber-protractor-template`](https://github.com/serenity-js/serenity-js-cucumber-protractor-template) to create a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and publish it to Github so that we can try to reproduce the problem you're seeing?

Also, could you please provide the version numbers of:
- Serenity/JS
- Protractor
- Chrome
- Node
- as well as the details of the operating system you're running your tests on?

Thanks,
Jan

**Comment by jan-molak** [comment] 2020-10-24 23:53
_Since the issue was raised, I've [created an example](https://github.com/serenity-js/serenity-js/blob/master/examples/protractor-cucumber/features/outlines.feature) demonstrating the usage of Cucumber scenario outlines with Protractor and Serenity/JS. Since the example describes a scenario very similar to the one presented by @lucieneven and gets reported correctly, I'm going to close this ticket_.

**Closed by jan-molak** 2020-10-24 23:53 UTC
Labels: awaiting feedback
