### ISSUE TITLE
[Cucumber rerun feature] TypeError: Cannot read property 'line' of undefined

### ISSUE THREAD

**Issue by Gump0422** [serenity-js/serenity-js#975] opened 2021-08-29 03:02 UTC
Hi, all
When using 

> rerun:@rerun.txt

Error: TypeError: Cannot read property 'line' of undefined
[rerun:execute]     at CucumberMessagesParser.scenarioDetailsFor (/Users/tab.wu/Study/cucum/serenity-js-cucumber-protractor-template/node_modules/@serenity-js/cucumber/src/listeners/messages/parser/CucumberMessagesParser.ts:185:26)
[rerun:execute]     at CucumberMessagesParser.parseTestCaseStarted (/Users/tab.wu/Study/cucum/serenity-js-cucumber-protractor-template/node_modules/@serenity-js/cucumber/src/listeners/messages/parser/CucumberMessagesParser.ts:87:37)
[rerun:execute]     at EventEmitter.CucumberMessagesListener.options.eventBroadcaster.on (/Users/tab.wu/Study/cucum/serenity-js-cucumber-protractor-template/node_modules/@serenity-js/cucumber/src/listeners/messages/CucumberMessagesListener.ts:50:41)
[rerun:execute]     at EventEmitter.emit (events.js:203:15)
[rerun:execute]     at EventEmitter.emit (domain.js:448:20)

Plz refer to example: 
https://github.com/Gump0422/serenity-js-cucumber-protractor-template 

You can run with commads: 
`npm install
`
`npm test
`
`npm rerun
`

**Comment by jan-molak** [comment] 2021-08-29 21:09
I can reproduce, thanks. Checking.

**Comment by jan-molak** [comment] 2021-08-30 23:30
OK, so I think I know what's going on.

Looks like Cucumber [doesn't like](https://github.com/cucumber/cucumber-js/blob/master/docs/cli.md#built-in-formatters) to be given _both_ the `@rerun.txt` file and the locations of other feature files to run, and that causes it to emit incorrect messages

**Comment by Gump0422** [comment] 2021-08-31 00:47
Hi @jan-molak,
What should I do to help finish rerun progress?

**Comment by jan-molak** [comment] 2021-08-31 01:35
Hi @Gump0422 - after a couple of hours of debugging I believe that the issue is with Cucumber.js, so am working on creating a repo demonstrating the problem and reporting that to the Cucumber team.

Thanks for offering to help; at the moment I think I just need to continue down this rabbit hole and make sure the problem is fixed at the source.

If you'd like to help me secure more time for open-source development of Serenity/JS and submitting this and other fixes to Cucumber, please consider becoming a [GitHub sponsor of Serenity/JS](https://github.com/sponsors/serenity-js).

**Comment by Gump0422** [comment] 2021-09-01 02:13
HI, @jan-molak 
Thanks for your nice work and support, Serenity/JS is a good test framework and I am so interested, I will consider your advice to be a sponsor of it, since I have a job now, I have to ensure it will not be conflict with my job.

**Comment by jan-molak** [comment] 2021-09-08 09:12
Confirmed bug in Cucumber.js - https://github.com/cucumber/cucumber-js/issues/1783

**Comment by viper3400** [comment] 2022-10-23 14:51
@jan-molak, issue should be solved in cucumber-js since version 8.4.0. 

Should be solved then in the latest Serenity/JS 3.0 RC as well:
https://github.com/serenity-js/serenity-js/blob/3480ba44d83ff663a6a7c3e51ab1f977776cc9d0/packages/cucumber/package.json#L65

Most likely not solved in the Serentiy/JS 2.x branch:
https://github.com/serenity-js/serenity-js/blob/0a7c900eea7d29e1647ea915150d7b66450126be/packages/cucumber/package.json#L68

**Comment by jan-molak** [comment] 2023-03-19 21:32
Closing as this issue should be resolved in 3.0.0-RC

**Closed by jan-molak** 2023-03-19 21:32 UTC
Labels: bug, @serenity-js/cucumber
