### ISSUE TITLE
Console reporter and Serenity-bdd report not showing the correct value executed using Scenario Outline Examples 

### ISSUE THREAD

**Issue by Nywlem** [serenity-js/serenity-js#678] opened 2020-10-07 14:52 UTC
Hi Team,

I noticed an issue with the console reporter and serenity-bdd report when Examples are used in the feature file(s).

For example:

```gherkin
Scenario Outline: User verifies the strings in the menu are translated
        When Select <Language> language
        * Save the language selection
        * User navigates to the menu
        Then Verify the language string in menu is translated to <Translation>

        Examples:
            | Language | Translation |
            | German   | Sprache     |
            | French   | Langue      |
            | English  | Language    |
```

![image](https://user-images.githubusercontent.com/23047616/95346968-05e94b00-08da-11eb-8ba3-4dfecdc3a65c.png)

![image](https://user-images.githubusercontent.com/23047616/95347177-3d57f780-08da-11eb-870f-c3d8918fca28.png)

![image](https://user-images.githubusercontent.com/23047616/95347692-cf600000-08da-11eb-9ca3-6aef067f84cc.png)

The "When" and "Then" statements printed on the report show always the first value in the table, though the tests are validated against the correct values. It created confusion in the reports as to what values were being tested.

**Comment by jan-molak** [comment] 2020-10-24 23:20
Hi @Nywlem! I'm not able to reproduce this issue locally. Would you be able to publish a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) based on the [template](https://github.com/serenity-js/serenity-js-cucumber-protractor-template) to Github? It can have empty step defs.

Thanks!
Jan

**Comment by jan-molak** [comment] 2021-01-23 03:02
Serenity/JS v **2.20.0** introduced support for Cucumber 7 and an updated version of the Serenity BDD reporting CLI.

Since I wasn't able to reproduce the issue you're seeing, @Nywlem, I'm going to close this ticket.
Please feel free to reopen it if you spot the same thing in the latest version.

Thanks!

**Closed by jan-molak** 2021-01-23 03:02 UTC
Labels: awaiting feedback
