### ISSUE TITLE
Report generation warnings Timeout exception

### ISSUE THREAD

**Issue by AbhineetSharmax** [serenity-js/serenity-js#685] opened 2020-10-23 07:14 UTC
Hi @jan-molak ,

Greetings!

Thanks for all your hardwork, i am being working with 2.0 with protractor cucumber FW and with each step moving forward, exploring the new functions implemented(specially the one with java script executer implementation) and its really usable.

Also there are few stuff that are bothering us, 
After the run gets completed, while generating report using
npm run test:report

getting the warnings like attached.
![IMG_20201023_123540](https://user-images.githubusercontent.com/40024241/96967451-2ac1fd00-152d-11eb-9192-ee77bbeee63f.jpg)

would request you to please help us here, or any way to supress these warnings. 
Thanks again.

Best Regards,
Abhineet Sharma

**Comment by jan-molak** [comment] 2020-10-24 23:25
CC @wakaleo

**Comment by jan-molak** [comment] 2021-01-23 02:59
Version 2.20 has introduced an updated version of the Serenity BDD reporting CLI.

@AbhineetSharmax - would you mind checking if you see this issue with the latest version as I wasn't able to reproduce it?

Thanks!

**Comment by basid09** [comment] 2021-05-15 01:33
Hi,
I am using CLI serenity-cli-2.3.31 .

For some of my plans the tests takes a long time almost 4-5 hours. While writing report, it runs for 10 minutes and timeouts.
I see some of the reports pages getting printed, but there is also below error - 

`build	15-May-2021 09:19:30	[test:report] -------------------------------
build	15-May-2021 09:19:30	[test:report] SERENITY COMMAND LINE INTERFACE
build	15-May-2021 09:19:30	[test:report] -------------------------------
build	15-May-2021 09:19:30	[test:report] Loading test outcomes from target/site/serenity
build	15-May-2021 09:19:30	[test:report] Writing aggregated report to target/site/serenity
build	15-May-2021 09:19:30	[test:report] 
build	15-May-2021 09:29:38	[test:report] 09:29:38.624 [main] WARN  n.t.c.r.h.HtmlAggregateStoryReporter - Report generation timed out for net.thucydides.core.reports.html.HtmlTestOutcomeReportingTask@7c214cc0 - java.util.concurrent.TimeoutException
build	15-May-2021 09:29:38	[test:report] java.util.concurrent.FutureTask.get(FutureTask.java:205)
build	15-May-2021 09:29:38	[test:report] 09:29:38.630 [main] WARN  n.t.c.r.h.HtmlAggregateStoryReporter - SOME REPORT PAGES COULD NOT BE GENERATED
build	15-May-2021 09:29:38	[test:report]  * Report generation timed out for net.thucydides.core.reports.html.HtmlTestOutcomeReportingTask@7c214cc0 - java.util.concurrent.TimeoutException
build	15-May-2021 09:29:38	[test:report] java.util.concurrent.FutureTask.get(FutureTask.java:205)
build	15-May-2021 09:29:38	[test:report] 
build	15-May-2021 09:29:38	[test:report] 
build	15-May-2021 09:29:38	[test:report] Report generation done
build	15-May-2021 10:13:14	[failsafe] Script 'test:report' exited with code 0`

**Comment by viper3400** [comment] 2022-10-23 14:58
Hi @basid09 , @AbhineetSharmax. It's been a while since the last posts in this issues. Do you still face problems? If yes, could you give an update about your current setup and current errors?

Otherwise I'd suggest to close this issue.

**Comment by viper3400** [comment] 2022-12-04 15:07
I guess we can close this issue. Please do not hesitate to raise a new one if the problem still exists. Just in case, please provide an update about your current setup and issues, then.

**Closed by viper3400** 2022-12-04 15:07 UTC
Labels: awaiting feedback
