### ISSUE TITLE
Rerun argument is not recognized

### ISSUE THREAD

**Issue by paolocarrasco** [serenity-js/serenity-js#321] opened 2019-05-29 13:13 UTC
**Question:**
Do we support the `rerun` feature from Cucumber in Serenity-JS?
If not, are there plans to support it? (maybe in version 2)

I'm trying to replay the failing tests by using this feature, which is supported by `protractor-cucumber-framework` (used by Serenity-JS for the cucumber flavor) but for some reason, the argument is not being recognized.

When I switch from Serenity to `protractor-cucumber-framework` as the custom framework in the protractor configuration file it does recognize it (but I lose the Serenity features):

From
```json
    framework: 'custom',
    frameworkPath: require.resolve('serenity-js'),
```
to
```json
    framework: 'custom',
    frameworkPath: require.resolve('protractor-cucumber-framework'),
```
it works

These are the details of my package.json:
```
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^1.6.0",
    "@typescript-eslint/parser": "^1.6.0",
    "cucumber": "1.3.2",
    "eslint": "^5.16.0",
    "eslint-config-airbnb-base": "^13.1.0",
    "eslint-plugin-import": "^2.14.0",
    "glob": "7.1.2",
    "npm-failsafe": "^0.4.1",
    "protractor-cucumber-framework": "5.0.0",
    "rimraf": "^2.6.3",
    "serenity-cli": "^0.11.1",
    "ts-node": "^8.0.2",
    "typescript": "^3.2.4"
  },
  "dependencies": {
    "@serenity-js/rest": "^1.1.1",
    "@types/chai": "4.0.0",
    "@types/chai-as-promised": "0.0.31",
    "@types/cucumber": "1.3.1",
    "@types/node": "7.0.31",
    "axios": "^0.18.0",
    "chai": "4.0.2",
    "chai-as-promised": "7.0.0",
    "js-yaml": "^3.13.0",
    "module-alias": "^2.2.0",
    "moment": "^2.24.0",
    "protractor": "5.3.2",
    "serenity-js": "^1.10.13"
}
```

**Comment by abhinaba1080** [comment] 2019-11-25 14:41
This will help you #101

**Comment by jan-molak** [comment] 2020-02-04 23:55
Closing as duplicate of #101

**Closed by jan-molak** 2020-02-04 23:55 UTC
Labels: duplicate
