### ISSUE TITLE
E2E script is not generating the HTML report

### ISSUE THREAD

**Issue by rakeshnambiar** [serenity-js/serenity-js#283] opened 2018-11-30 15:12 UTC
I am using the below command to run the test. It's taking the screenshot and there's no html files in the target folder [\target\site\serenity].
npm run e2e -- --tag @RegressionTest --browser chrome --baseUrl http://myapp.com
OR
npm run e2e -- --baseUrl="http://http://myapp.com" --cucumberOpts.tags="@RegressionTest" --browser="chrome"

Package.json looks like below:
    "e2e": "protractor ./protractor.conf.js",
    "test": "failsafe e2e report"

I tried something like:

npm run test -- --baseUrl="http://lmyapp.com" --cucumberOpts.tags="@RegressionTest" --browser="firefox" now the HTML report is generated. However, it's ignored the run parameters.

**Comment by rakeshnambiar** [comment] 2018-12-04 15:45
@jan-molak could you please check and advise on this?

**Comment by jan-molak** [comment] 2018-12-04 21:56
Hi @rakeshnambiar. So is your test run generating the screenshots and the `json` reports, but not the html reports?

**Comment by rakeshnambiar** [comment] 2018-12-04 22:01
@jan-molak thanks for your response. 

The 'npm run e2e' command generates only the screenshot and not the json or html reports.

**Comment by rakeshnambiar** [comment] 2018-12-14 11:42
@jan-molak appreciate any help on this

**Comment by srinivasbudh** [comment] 2019-02-11 13:27
Hi @jan-molak I have a similar problem, Screenshots are being captured but not the HTML Reports

**Comment by marktigno** [comment] 2019-02-12 03:45
have you tried including this in your package.json "scripts" section: `"report": "serenity run"`

**Comment by rakeshnambiar** [comment] 2019-02-12 09:49
@marktigno it's already there. I am facing this issue while overriding the parameters through command line.

**Comment by jan-molak** [comment] 2019-02-12 15:43
@rakeshnambiar, @srinivasbudh - would you be able to create a minimal project demonstrating the issue on github? I'd love to help, but it's difficult without being able to see what you see.

**Comment by rakeshnambiar** [comment] 2019-02-12 15:45
@jan-molak make-sense. I will share the project. Thanks a lot.

**Comment by rakeshnambiar** [comment] 2019-02-12 16:27
@jan-molak Please clone the below repo.

https://github.com/rakeshnambiar/serenityjs.git

When I try 'npm install-test' everything is perfect, but not working when I use the command 'npm run e2e'. I will have to use this command to override the run parameters through Jenkins.

**Comment by jan-molak** [comment] 2020-03-10 17:09
Hi @rakeshnambiar - could you please see if you can reproduce this scenario with Serenity/JS 2.0?
You might want to use the [`serenity-js-cucumber-protractor-template` repo](https://github.com/serenity-js/serenity-js-cucumber-protractor-template)

**Comment by viper3400** [comment] 2022-05-15 08:41
Hi @rakeshnambiar, I'm going through all open issues in this project. It's been a while since the last comment and the issue seems to target [Serenity/JS 1.x](https://github.com/rakeshnambiar/serenityjs/blob/40ba3b35f077798458ff696708cfe2f1a0ba6283/script/package.json#L33). Have you found a solution or do you still face problems in this area?

**Comment by viper3400** [comment] 2022-06-18 07:45
Hi everyone, okay, so let's close this issue. Please raise a new one if you still face problems using Serentiy/JS.

**Closed by viper3400** 2022-06-18 07:45 UTC
Labels: awaiting feedback
