### ISSUE TITLE
Reports not showing capabilities or features under their respective tabs when produced with serenity-cli:jar 3.6.12

### ISSUE THREAD

**Issue by eoinreilly93** [serenity-js/serenity-js#1649] opened 2023-04-17 11:52 UTC
Hi Jan,

When running SerenityJS and generating a report using the serenity-cli:jar version 3.6.12, I am not seeing any data under the Capabilities or Features section of the report. If I generate a report with serenity java on the same version, I am seeing this data under these tabs. And if I generate a report with the combination of these two tests, I only see the java tests under there. 

Please see a reproducible example on my [github](https://github.com/eoinreilly93/SerenityExample) that you can clone for debugging purposes

Thanks!

**Comment by eoinreilly93** [comment] 2023-04-19 10:30
Hi @jan-molak,

Thanks very much for the swift fix. However I have noticed that with the addition of additional README files to the project, the report formatting again appears to have broken. I have pushed the changes to my repo again for you to be able to reproduce, but you can see in the screenshot attached, that now the Capabilities tab is now gone and looks to have been merged into the Themes tab. 

I think this issue may need to be reopened again. 

If you have any questions please let me know!

<img width="1501" alt="Screenshot 2023-04-19 at 11 27 56" src="https://user-images.githubusercontent.com/26492462/233048021-87e24daa-28a0-4c5d-a643-8d1d61b31cb3.png">

**Comment by jan-molak** [comment] 2023-04-19 23:11
Hey @eoinreilly93 - it seems like a bug in Serenity BDD; I raised it under https://github.com/serenity-bdd/serenity-core/issues/3119 an will update you when I find out more.

**Comment by jan-molak** [comment] 2023-04-25 08:14
Hi @eoinreilly93 - the issue is fixed in Serenity BDD `3.6.23`, as you can see in [my fork](https://github.com/jan-molak/serenity-js-issue-1649/tree/bug/nested-readmes)

Could you please let me know if upgrading to Serenity BDD 3.6.23 addresses the issue on your side too?

**Comment by eoinreilly93** [comment] 2023-05-08 17:46
Hi @jan-molak,

Thanks, I can confirm this issue is now fixed. I have noticed some additional report issues, but I will raise them under a separate issue on the serenity-bdd project. Thanks for you help1

**Closed** 2023-05-08 19:27 UTC
Labels: bug
