### ISSUE TITLE
integration with Jira/XRAY doesnt work as it doesnt update result or attach report.

### ISSUE THREAD

**Issue by AnnneN** [serenity-js/serenity-js#1952] opened 2023-09-25 15:36 UTC
### What happened?

I need to integrate my test execution run with JIRA/XRAY. At the moment, I am only able to link or tag the feature with JIRA but it what is required is to update the test execution run and attach a copy of test results.
I was not able to find solution to this in serenity however in pytest its fairly simple and achieved with the help of a annotation.
refer below link:
https://pypi.org/project/pytest-jira-xray/

Please let me know if we have already something like this, at the moment I am only aware of the below:
https://serenity-js.org/handbook/integration/jira-and-other-issue-trackers/

### What did you expect to happen?

To update the test result and attach the copy of test results

### Serenity/JS version

```shell
3.9.0
```

### Node.js version

20

### How to reproduce the bug.

Use the link 
https://serenity-js.org/handbook/integration/jira-and-other-issue-trackers/

**Comment by jan-molak** [comment] 2023-09-25 16:25
This looks like a duplicate of #1951

**Closed by jan-molak** 2023-09-25 16:25 UTC
