### ISSUE TITLE
does serenityjs has xml report like junit?

### ISSUE THREAD

**Issue by boya678** [serenity-js/serenity-js#325] opened 2019-06-20 15:35 UTC
does serenityjs has xml report like junit?

**Comment by jan-molak** [comment] 2019-06-20 22:32
Hi @boya678! It doesn't have any dedicated XML reporter (yet), but you could attach a JUnit reporter to the test runner itself, here's an example for Mocha - https://www.npmjs.com/package/mocha-junit-reporter

Does this help?

**Comment by jan-molak** [comment] 2020-02-04 23:53
Closing as a duplicate of #346; Could we continue our conversation under that ticket, @boya678?

**Closed by jan-molak** 2020-02-04 23:53 UTC
Labels: duplicate

**Comment by abhinaba1080** [comment] 2020-03-14 14:25
@boya678  Can I provide a workaround?

cucumber-junit-convert can be your friend in this case:

```js
npm i --save-dev cucumber-junit-convert
```

in your protractor conf, add format options to emit cucumber results in a JSON format to a specific file, like:

```js
cucumberOpts: {
    format: ['pretty', 'json:target/cucumber_report.json'],
    'format-options': '{"colorsEnabled": true }',
    require: [`${process.cwd()}/transform/**/*.js`],
    compiler: 'ts:ts-node/register'
  }
```

Then create a JS file which will convert this JSON report to JUNIT style report. Let's say, the file name is **jenkins.report.js**

```js
const cucumberJunitConvert = require('cucumber-junit-convert');

const options = {
  inputJsonFile: 'target/cucumber_report.json',
  outputXmlFile: 'target/cucumber_report.xml'
};

cucumberJunitConvert.convert(options);

```

You can add the conversion process  to the serenity report step in your package.json like:

```js
 "report": "serenity run --cacheDir ./lib/serenity-cli && node ./jenkins.report.js",
```
Now, every time you produce Serenity HTML reports, it will generate a JUNIT style report as well in specified folder.
