### ISSUE TITLE
Serenity-js fails to run with "--format message" option (with VSC cucumber test runner)

### ISSUE THREAD

**Issue by danielvanmil** [serenity-js/serenity-js#2499] opened 2024-08-25 16:30 UTC
### What happened?

I want to use Visual Studio Code Cucumber Test Runner (https://marketplace.visualstudio.com/items?itemName=balrog994.cucumber-test-runner).

The extension runs cucumber.js with the "--format message" option which might not be supported by SerenityJS?

When I run for example https://github.com/serenity-js/serenity-js-cucumber-playwright-template the following error can be seen:

```
Error: an AfterAll hook errored, process exiting: features\support\serenity.config.ts:58
    at Runtime.runTestRunHooks (C:\Users\danielm\AppData\Local\Yarn\Berry\cache\@cucumber-cucumber-npm-10.3.1-5a0451b989-10c0.zip\node_modules\@cucumber\cucumber\src\runtime\run_test_run_hooks.ts:33:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Runtime.start (C:\Users\danielm\AppData\Local\Yarn\Berry\cache\@cucumber-cucumber-npm-10.3.1-5a0451b989-10c0.zip\node_modules\@cucumber\cucumber\src\runtime\index.ts:120:5)
    at async runCucumber (C:\Users\danielm\AppData\Local\Yarn\Berry\cache\@cucumber-cucumber-npm-10.3.1-5a0451b989-10c0.zip\node_modules\@cucumber\cucumber\src\api\run_cucumber.ts:145:19)
    at async Cli.run (C:\Users\danielm\AppData\Local\Yarn\Berry\cache\@cucumber-cucumber-npm-10.3.1-5a0451b989-10c0.zip\node_modules\@cucumber\cucumber\src\cli\index.ts:79:25)
    at async Object.run [as default] (C:\Users\danielm\AppData\Local\Yarn\Berry\cache\@cucumber-cucumber-npm-10.3.1-5a0451b989-10c0.zip\node_modules\@cucumber\cucumber\src\cli\run.ts:32:14) {
  [cause]: Error: 1 async operation has failed to complete:
  [Photographer:TakePhotosOfFailures] Taking screenshot of 'Alice ensures that page element located by css ('engatta-main') does become present'... - browserContext.newPage: Protocol error (Target.createTarget): Failed to open a new tab
      at PlaywrightBrowsingSessionWithBrowser.registerCurrentPage (C:\Users\danielm\AppData\Local\Yarn\Berry\cache\@serenity-js-playwright-npm-3.17.0-1ec33d656c-10c0.zip\node_modules\@serenity-js\playwright\src\screenplay\models\PlaywrightBrowsingSessionWithBrowser.ts:28:23)
      at async PlaywrightBrowsingSessionWithBrowser.currentPage (C:\Users\danielm\AppData\Local\Yarn\Berry\cache\@serenity-js-web-npm-3.17.0-1c3845ce79-10c0.zip\node_modules\@serenity-js\web\src\screenplay\models\BrowsingSession.ts:44:39)
      at async TakePhotosOfFailures.considerTakingPhoto (C:\Users\danielm\AppData\Local\Yarn\Berry\cache\@serenity-js-web-npm-3.17.0-1c3845ce79-10c0.zip\node_modules\@serenity-js\web\src\stage\crew\photographer\strategies\PhotoTakingStrategy.ts:57:35)
  ---

      at StageManager.waitForNextCue (C:\Users\danielm\AppData\Local\Yarn\Berry\cache\@serenity-js-core-npm-3.17.0-55933a507a-10c0.zip\node_modules\@serenity-js\core\src\stage\StageManager.ts:57:27)
      at async PerformActivities.perform (C:\Users\danielm\AppData\Local\Yarn\Berry\cache\@serenity-js-core-npm-3.17.0-55933a507a-10c0.zip\node_modules\@serenity-js\core\src\screenplay\abilities\PerformActivities.ts:62:13)
      at async PerformActivities.perform (C:\Users\danielm\AppData\Local\Yarn\Berry\cache\@serenity-js-core-npm-3.17.0-55933a507a-10c0.zip\node_modules\@serenity-js\core\src\screenplay\abilities\PerformActivities.ts:53:13)
      at async PerformActivities.perform (C:\Users\danielm\AppData\Local\Yarn\Berry\cache\@serenity-js-core-npm-3.17.0-55933a507a-10c0.zip\node_modules\@serenity-js\core\src\screenplay\abilities\PerformActivities.ts:53:13)
```

### What did you expect to happen?

Expected to output the test successfully.

### Node.js version

v20.11.0

### Execution environment

Windows

### How to reproduce the bug.

- Install Visual Studio Code
- Install the https://marketplace.visualstudio.com/items?itemName=balrog994.cucumber-test-runner extension
- Clone https://github.com/serenity-js/serenity-js-cucumber-playwright-template
- Run a test with the explorer

Expected: all goes well
Actual: An error is thrown, see stacktrace in description

### Serenity/JS version

```shell
"@serenity-js/assertions": "^3.17.0",
    "@serenity-js/console-reporter": "^3.17.0",
    "@serenity-js/core": "^3.17.0",
    "@serenity-js/cucumber": "^3.17.0",
    "@serenity-js/playwright": "^3.17.0",
    "@serenity-js/rest": "^3.17.0",
    "@serenity-js/serenity-bdd": "^3.17.0",
    "@serenity-js/web": "^3.17.0",
```

**Comment by jan-molak** [comment] 2024-08-27 12:36
Hi @danielvanmil. I'm not able to reproduce it with a fresh VSCode installation and a fresh clone of the project template:
<img width="1136" alt="Screenshot 2024-08-27 at 14 28 47" src="https://github.com/user-attachments/assets/db1b906b-489d-4dc8-9034-ac88a46990f5">

I did notice a couple of things in the stack trace, though:
- It seems that you're using Yarn Berry. Have you tried installing the dependencies via `npm ci` instead? 
- The stack trace mentions that the actor cannot locate a `page element by css ('engatta-main')`. This selector is not used anywhere in the template's codebase, so could this be caused by some modification you've made?
- The stack trace mentions an issue could be related to an async operation. If you've made any modifications to the template, did you remember to add `await` before `actor.attemptsTo` in your step definitions?

**Comment by jan-molak** [comment] 2024-09-06 16:34
@danielvanmil - I'll close this issue as it doesn't seem related to Serenity/JS code, and I could not reproduce it.

**Closed by jan-molak** 2024-09-06 16:34 UTC
